index:
    path: /
    controller: App\Controller\ProductController::index

product_show:
    path: /product/{id}
    controller: App\Controller\ProductController::show

admin:
    path: /admin
    controller: App\Controller\DefaultController::admin
