index:
    path: /
    controller: App\Controller\ProductController::index

product_show:
    path: /product/{id}
    controller: App\Controller\ProductController::show

admin_index:
    path: /admin
    controller: App\Controller\AdminController::index

admin_productEditor:
    path: /admin/product-editor/{id}
    controller: App\Controller\AdminController::productEditor
    defaults: { id: null }

basket_show:
    path: /basket
    controller: App\Controller\BasketController::show

basket_add:
    path: /basket/add/{id}
    controller: App\Controller\BasketController::add

basket_remove:
    path: /basket/remove/{id}
    controller: App\Controller\BasketController::remove

basket_update:
    path: /basket/update
    controller: App\Controller\BasketController::update

user_welcome:
    path: /user/welcome
    controller: App\Controller\UserController::welcome

user_login:
    path: /internal/login
    controller: App\Controller\UserController::login

user_register:
    path: /internal/register
    controller: App\Controller\UserController::register

user_logout:
    path: /user/logout

user_account:
    path: /user/account
    controller: App\Controller\UserController::account
