index:
    path: /
    controller: App\Controller\ProductController::index

product_show:
    path: /product/{id}
    controller: App\Controller\ProductController::show

product_delete:
    path: /admin/delete-product/{id}
    controller: App\Controller\ProductController::delete

admin_index:
    path: /admin
    controller: App\Controller\AdminController::index

admin_product-editor:
    path: /admin/product-editor/{id}
    controller: App\Controller\AdminController::productEditor
    defaults: { id: null }

admin_all-products:
    path: /admin/all-products
    controller: App\Controller\AdminController::allProducts

basket_show:
    path: /basket
    controller: App\Controller\BasketController::show

basket_add:
    path: /basket/add/{id}
    controller: App\Controller\BasketController::add

basket_remove:
    path: /basket/remove/{id}
    controller: App\Controller\BasketController::remove

basket_update:
    path: /basket/update
    controller: App\Controller\BasketController::update

user_welcome:
    path: /user/welcome
    controller: App\Controller\UserController::welcome

user_login:
    path: /internal/login
    controller: App\Controller\UserController::login

user_register:
    path: /internal/register
    controller: App\Controller\UserController::register

user_logout:
    path: /user/logout

user_account:
    path: /user/account
    controller: App\Controller\UserController::account

user_edit-address:
    path: /user/account/edit-address
    controller: App\Controller\UserController::editAddress

user_change-password:
    path: /user/account/change-password
    controller: App\Controller\UserController::changePassword

paypal_checkout:
    path: /checkout/paypal
    controller: App\Controller\Payments\PaypalController::paypalCheckout

paypal_payment:
    path: /checkout/success
    controller: App\Controller\Payments\PaypalController::paypalPayment
